<div class="container">
    <div class="row profile">
        <div class="col-md-3">
            <div class="profile-sidebar">
                <!-- SIDEBAR USERPIC -->
                <div class="profile-userpic">
                    <img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg" class="img-responsive" alt="">
                </div>
                <!-- END SIDEBAR USERPIC -->
                <!-- SIDEBAR USER TITLE -->
                <div class="profile-usertitle">
                    <div class="profile-usertitle-name">
                        Marcus Doe
                    </div>
                    <div class="profile-usertitle-job">
                        Developer
                    </div>
                </div>
                <!-- END SIDEBAR USER TITLE -->
                <!-- SIDEBAR BUTTONS -->
                <div class="profile-userbuttons">
                    <button type="button" class="btn btn-success btn-sm">Perfil</button>
                    <button type="button" class="btn btn-danger btn-sm">Configurações</button>
                </div>
                <!-- END SIDEBAR BUTTONS -->
                <!-- SIDEBAR MENU -->
                <div class="profile-usermenu">
                    <ul class="nav">
                        <li class="active">
                            <a href="#">
                                <i class="glyphicon glyphicon-home"></i>
                                Linha do Tempo </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="glyphicon glyphicon-comment"></i>
                                Mensagens</a>
                        </li>
                        <li>
                            <a href="#" target="_blank">
                                <i class="glyphicon glyphicon-camera"></i>
                                Fotos </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="glyphicon glyphicon-facetime-video"></i>
                                Vídeos </a>
                        </li>
                    </ul>
                </div>
                <!-- END MENU -->
            </div>
        </div>

        <div class="col-md-7">
            <div class="col-md-12">
                <div class="no-padding blank">
                    <div class="status-upload">
                        <?php echo $this->form()->openTag($form); ?>
                            <?php echo $this->formRow($form->get('publicacao')); ?>
                            <ul>
                                <li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Localização"><i class="glyphicon glyphicon-map-marker"></i></a></li>
                                <li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Vídeo"><i class="glyphicon glyphicon-facetime-video"></i></a></li>
                                <li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Foto"><i class="glyphicon glyphicon-camera"></i></a></li>
                            </ul>

                            <button type="submit" class="btn btn-success green"><i class="glyphicon glyphicon-share-alt"></i> Publicar</button>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>

            <div class="col-md-12">
                <div class="panel panel-default panel-google-plus">
                    <div class="panel-heading">
                        <img class="img-circle pull-left" src="https://lh3.googleusercontent.com/-CxXg7_7ylq4/AAAAAAAAAAI/AAAAAAAAAQ8/LhCIKQC5Aq4/s46-c-k-no/photo.jpg" alt="Mouse0270" />
                        <h3>Robert McIntosh</h3>
                        <h5><span>Shared publicly</span> - <span>Jun 27, 2014</span> </h5>
                    </div>
                    <div class="panel-body">
                        <p>Do people born in 2000 get to choose if they are Generation Y or Generation Z? How do you decide what generation you want to belong to?</p>
                    </div>
                    <div class="panel-footer">
                        <button type="button" class="btn btn-sm btn-success" onclick="startSpinner()">
                            <span class="glyphicon glyphicon-thumbs-up"></span> Gostei
                        </button>
                        <button type="button" class="btn btn-sm btn-danger" onclick="stopSpinner()">
                            <span class="glyphicon glyphicon-thumbs-down"></span> Não Gostei
                        </button>
                        <button type="button" class="btn btn-sm btn-primary input-placeholder">
                            <span class="glyphicon glyphicon-arrow-right"></span> Comentar
                        </button>
                    </div>
                    <div class="panel-google-plus-comment">
                        <img class="img-circle" src="https://lh3.googleusercontent.com/uFp_tsTJboUY7kue5XAsGA=s46" alt="User Image" />
                        <div class="panel-google-plus-textarea">
                            <textarea rows="4"></textarea>
                            <button type="submit" class="btn btn-sm btn-success disabled">Comentar</button>
<!--                            <button type="reset" class="btn btn-sm btn-danger">Cancelar</button>-->
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>



        </div>

        <div class="col-md-2">
            <div class="profile-content">

            </div>
        </div>

    </div>
</div>
