<div class="container">
    <div class="row profile">
        <div class="col-md-3">
            <div class="profile-sidebar">
                <!-- SIDEBAR USERPIC -->
                <div class="profile-userpic">
                    <img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg" class="img-responsive" alt="">
                </div>
                <!-- END SIDEBAR USERPIC -->
                <!-- SIDEBAR USER TITLE -->
                <div class="profile-usertitle">
                    <div class="profile-usertitle-name">
                        Marcus Doe
                    </div>
                    <div class="profile-usertitle-job">
                        Developer
                    </div>
                </div>
                <!-- END SIDEBAR USER TITLE -->
                <!-- SIDEBAR BUTTONS -->
                <div class="profile-userbuttons">
                    <button type="button" class="btn btn-success btn-sm">Perfil</button>
                    <button type="button" class="btn btn-danger btn-sm">Configurações</button>
                </div>
                <!-- END SIDEBAR BUTTONS -->
                <!-- SIDEBAR MENU -->
                <div class="profile-usermenu">
                    <ul class="nav">
                        <li class="active">
                            <a href="#">
                                <i class="glyphicon glyphicon-home"></i>
                                Linha do Tempo </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="glyphicon glyphicon-comment"></i>
                                Mensagens</a>
                        </li>
                        <li>
                            <a href="#" target="_blank">
                                <i class="glyphicon glyphicon-camera"></i>
                                Fotos </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="glyphicon glyphicon-facetime-video"></i>
                                Vídeos </a>
                        </li>
                    </ul>
                </div>
                <!-- END MENU -->
            </div>
        </div>

        <div class="col-md-7">
            <div class="col-md-12">
                <div class="no-padding blank">
                    <div class="status-upload">
                        <form>
                            <textarea placeholder="Compartilhe algo com seus amigos" ></textarea>
                            <ul>
                                <li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Localização"><i class="glyphicon glyphicon-map-marker"></i></a></li>
                                <li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Vídeo"><i class="glyphicon glyphicon-facetime-video"></i></a></li>
                                <li><a title="" data-toggle="tooltip" data-placement="bottom" data-original-title="Foto"><i class="glyphicon glyphicon-camera"></i></a></li>
                            </ul>
                            <button type="submit" class="btn btn-success green"><i class="glyphicon glyphicon-share-alt"></i> Publicar</button>
                        </form>
                    </div><!-- Status Upload  -->
                </div><!-- Widget Area -->
            </div>
        </div>

        <div class="col-md-2">
            <div class="profile-content">

            </div>
        </div>

    </div>
</div>